### PR TITLE
don't promisify `walk`

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by overlookmotel** [comment]
`walk` method is no longer part of the API as of `fs-extra` v2.0.0. So closing this issue as no longer relevant.

Sorry I didn't act fast enough to have made the change while it *was* still relevant!

**Comment by refack** [comment]
NM

**Comment by overlookmotel** [comment]
NM??

**Comment by refack** [comment]
Never Mind... 😎

**Pull request closed without merging**
